In [55]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import pprint

# Import API key
from config import google_api_key

In [56]:
#load part 1 weather data and create new df
path = "Analysis/WeatherAPI/weather_df.csv"
weather_df = pd.read_csv(path)
weather_df.head()

,City Name,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Latitude,Longitude
0,Oktyabr'skiy,48.15,50,55,6.20,54.4815,53.4710
1,Pangnirtung,32.00,93,75,3.44,66.1451,-65.7125
2,Shenjiamen,62.06,85,7,15.84,29.9576,122.2980
3,Sisimiut,39.42,69,42,5.41,66.9395,-53.6735
4,Caravelas,79.18,67,87,11.68,-17.7125,-39.2481

In [57]:
weather_df.dtypes

City Name               object
Max Temperature (F)    float64
Humidity (%)             int64
Cloudiness (%)           int64
Wind Speed (mph)       float64
Latitude               float64
Longitude              float64
dtype: object

In [58]:
gmaps.configure(api_key = google_api_key)

city_locations = weather_df[["Latitude", "Longitude"]]
humidity = weather_df["Humidity (%)"].astype(float)

fig = gmaps.figure(map_type = "HYBRID")

heat_layer = gmaps.heatmap_layer(city_locations, weights=humidity, 
                                 dissipating=False, max_intensity = 100,
                                 point_radius=3, opacity=0.5)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [59]:
# create new df for hotel search
hotel_df = weather_df.loc[((weather_df["Max Temperature (F)"]>70) &
                         (weather_df["Max Temperature (F)"]<80) &
                         (weather_df["Wind Speed (mph)"]<10) &
                         (weather_df["Cloudiness (%)"]==0)),:]

hotel_df = hotel_df.dropna(how = "any")
hotel_df.head()

,City Name,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Latitude,Longitude
72,Saint-Philippe,77.00,83,0,4.61,-21.3585,55.7679
98,Chui,70.34,47,0,7.87,-33.6971,-53.4616
127,Saint-Leu,77.00,83,0,4.61,-21.1500,55.2833
145,Villa María,71.01,55,0,4.00,-32.4075,-63.2402
153,Necochea,73.99,47,0,8.01,-38.5473,-58.7368

In [60]:
# Hotel Map (nearest places file)
hotel_df["Hotel Name"] = ""
hotel_df.head()

,City Name,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Latitude,Longitude,Hotel Name
72,Saint-Philippe,77.00,83,0,4.61,-21.3585,55.7679,
98,Chui,70.34,47,0,7.87,-33.6971,-53.4616,
127,Saint-Leu,77.00,83,0,4.61,-21.1500,55.2833,
145,Villa María,71.01,55,0,4.00,-32.4075,-63.2402,
153,Necochea,73.99,47,0,8.01,-38.5473,-58.7368,

In [65]:
for index, row in hotel_df.iterrows():

    # Grab the city information from the DataFrame Row
    city = row["City Name"]
    lat = row["Latitude"]
    lng = row["Longitude"]
       
    params = {
              "location": f"{lat},{lng}",
              "types": "lodging",
              "radius": 5000,
              "key": google_api_key,
             }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json" 
               
    response = requests.get(base_url, params=params).json()
        
    # Get the results
    results = response["results"]
    
    try:
        name = results[0]['name']
        print(f"Nearest hotel to {city} is {name}.")        
        hotel_df.loc[index, "Hotel Name"] = name
        
    except (KeyError, IndexError):
        print(f"Error with city={city}, skipping...")
        hotel_df.loc[index, "Hotel Name"] = "NaN"
    
hotel_df

Nearest hotel to Saint-Philippe is Chambres d'hôte "La Trinité".
Nearest hotel to Chui is Nuevo Hotel Plaza.
Nearest hotel to Saint-Leu is La Caz Oceane.
Nearest hotel to Villa María is Hotel Milenium.
Nearest hotel to Necochea is dyd -mar Hotel.
Nearest hotel to Gelibolu is Oya Hotel.
Nearest hotel to Luján is Hotel Biarritz.
Nearest hotel to Saint-Joseph is "Plantation Bed and Breakfast.
Nearest hotel to Mercedes is Posada del Inti Centro.
Nearest hotel to Shaki is Hotel Sheki Azpetrol.
Nearest hotel to Noumea is Hôtel Le Lagon.
Nearest hotel to Guerrero Negro is Casa Laguna, Bed & Breakfast.
Nearest hotel to San Quintín is Don Eddie's Sport Fishing Center.
Nearest hotel to La Libertad is Playa Canela Hotel Boutique.
Nearest hotel to Qingquan is Caiyuan Hotel.
Nearest hotel to Port Hedland is The Esplanade Hotel.
Nearest hotel to Bǝrdǝ is Prins Motel Restoran.
Nearest hotel to Kumul is Laoyutang Resort.
Nearest hotel to São Borja is Hotel Executivo.

,City Name,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Latitude,Longitude,Hotel Name
72,Saint-Philippe,77.00,83,0,4.61,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
98,Chui,70.34,47,0,7.87,-33.6971,-53.4616,Nuevo Hotel Plaza
127,Saint-Leu,77.00,83,0,4.61,-21.1500,55.2833,La Caz Oceane
145,Villa María,71.01,55,0,4.00,-32.4075,-63.2402,Hotel Milenium
153,Necochea,73.99,47,0,8.01,-38.5473,-58.7368,dyd -mar Hotel
166,Gelibolu,71.60,60,0,6.91,40.4103,26.6708,Oya Hotel
240,Luján,72.00,54,0,8.01,-34.5703,-59.1050,Hotel Biarritz
276,Saint-Joseph,77.00,83,0,4.61,-21.3667,55.6167,"""Plantation Bed and Breakfast"
305,Mercedes,73.99,54,0,8.01,-34.6515,-59.4307,Posada del Inti Centro
333,Shaki,73.40,56,0,3.44,41.0833,47.1667,Hotel Sheki Azpetrol
356,Noumea,75.00,68,0,2.30,-22.2763,166.4572,Hôtel Le Lagon
368,Guerrero Negro,73.87,44,0,8.32,27.9769,-114.0611,"Casa Laguna, Bed & Breakfast"
369,San Quintín,75.61,38,0,5.91,30.4833,-115.9500,Don Eddie's Sport Fishing Center
441,La Libertad,77.00,83,0,9.22,-2.2333,-80.9000,Playa Canela Hotel Boutique
469,Qingquan,71.08,78,0,3.24,30.4511,115.2559,Caiyuan Hotel
473,Port Hedland,73.40,83,0,8.05,-20.3167,118.5667,The Esplanade Hotel
492,Bǝrdǝ,73.40,56,0,3.44,40.3744,47.1267,Prins Motel Restoran
507,Kumul,76.57,12,0,3.31,42.8000,93.4500,Laoyutang Resort
544,São Borja,75.83,40,0,7.83,-28.6606,-56.0044,Hotel Executivo

In [68]:
# Using the template add the hotel marks to the heatmap

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

KeyError: 'City'

In [67]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
info_layer = gmaps.symbol_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# fig.add_layer(info_layer)
# Display Map
fig

NameError: name 'locations' is not defined